import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RecoilContextProvider from './recoilContextProvider'
import Header from './components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilContextProvider>
          <Header />
          <div className='flex flex-col justify-center items-center pt-[20vh]'>
              {children}
          </div>
        </RecoilContextProvider>
      </body>
    </html>
  )
}
